######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 13 12:27:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CTemp.h DBTools.h frm_Main.h frm_MenuList.h frm_Result.h
FORMS += frm_Main.ui frm_MenuList.ui frm_Result.ui
SOURCES += CTemp.cpp frm_Main.cpp frm_MenuList.cpp frm_Result.cpp main.cpp
QT += sql
