######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 17 02:11:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connection.h edit.h menu.h order.h
FORMS += edit.ui menu.ui order.ui
SOURCES += edit.cpp main.cpp menu.cpp order.cpp

QT += sql
